### DISCUSSION TITLE
how to properly add google analytics tag

### DISCUSSION THREAD

**Discussion by matikepa** [chrede88/qubt#172] [Q&A] [answered]
HI 
i have tried to add it in params.yaml like
```
services:
  googleAnalytics:
    id: G-xxx
```
also tried in hugo.yaml 
```
params:
  env: production 
  analytics:
    google:
      SiteVerificationTag: "G-xxx"
```

unfortunately none of this is working
